SELECT 
    ZOBJECT.*,
    ZSTRUCTUREDMETADATA.*,
    ZSOURCE.*,
    ZSYNCPEER.*,
    (ZOBJECT.ZENDDATE - ZOBJECT.ZSTARTDATE) AS usage,
    (ZOBJECT.ZSTARTDATE + 978307200) AS start_time,
    (ZOBJECT.ZENDDATE + 978307200) AS end_time,
    (ZOBJECT.ZCREATIONDATE + 978307200) AS created_at
FROM ZOBJECT
LEFT JOIN
ZSTRUCTUREDMETADATA ON ZOBJECT.ZSTRUCTUREDMETADATA = ZSTRUCTUREDMETADATA.Z_PK
LEFT JOIN
ZSOURCE ON ZOBJECT.ZSOURCE = ZSOURCE.Z_PK
LEFT JOIN
ZSYNCPEER ON ZSOURCE.ZDEVICEID = ZSYNCPEER.ZDEVICEID
ORDER BY ZOBJECT.ZSTARTDATE DESC